version: '3.7'
services:
  db:
    image: library/postgres:12
    container_name: db-postgre
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=queue
    ports:
      - 5434:5432
    volumes:
      - ${WORK_DATA}/database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d